# fly.toml app configuration file generated for bmilcs-inventory on 2023-07-08T12:45:51-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bmilcs-inventory"
primary_region = "bos"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  source="bmilcs_inventory"
  destination="/app/public/images"